# Makefile for algoritms for sorting

all: insert.c swap.c mergesort.c qsort.c buble.c
	gcc -o insert insert.c -std=gnu99 -Wall
	gcc -o swap swap.c -std=gnu99 -Wall
	gcc -o mergesort mergesort.c -std=gnu99 -Wall
	gcc -o qsort qsort.c -std=gnu99 -Wall
	gcc -o buble buble.c -std=gnu99 -Wall
